name: Deploy preview

on:
  pull_request:
    branches:
      - '*'

jobs:
  supabase-test:
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Link project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - name: Migrate database
        run: supabase db push --dry-run
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: supabase-test

    permissions:
      pull-requests: write
      contents: read

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{@{'
          tokenSuffix: '}@}'
          files: '["**/next.config.js"]'
        env:
          NEXT_PUBLIC_JUPYTERLITE_URL: ${{ vars.NEXT_PUBLIC_JUPYTERLITE_URL }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install the dependencies
        run: |
          pnpm install
      - name: Lint check
        run: |
          pnpm lint && pnpm prettier
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | tee deploy.log
      - id: seturl
        name: Set preview url
        run: echo "url=$(tail -1 deploy.log)">> $GITHUB_OUTPUT
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Preview URL**: ${{ steps.seturl.outputs.url }}
